// ERZEUGT von asset/calibration/fields/harvest_field_docs.py — nicht
// von Hand aendern. Quelle sind die Doxygen-Kommentare an den Feldern
// der `…Params`-Structs in EffectChain.hpp; wer einen Text aendern
// will, aendert ihn dort und laesst den Ernter neu laufen.
//
// Knoten-Parameter-Konzept §10 — Tooltip an jedem Feld.

#include "UI/panels/FieldDocs.hpp"

#include <algorithm>
#include <array>
#include <string_view>
#include <utility>

namespace lumi::multieffect::fielddocs
{
namespace
{
// Nach Schluessel sortiert — die Suche unten setzt das voraus.
constexpr std::array<std::pair<std::string_view, std::string_view>,
                     735>
    kDocs{{
    {"addBorders.beatCode",
     "Parameter-Skript (Strang D): `size` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"addBorders.color",
     "border colour 0x00RRGGBB"},
    {"addBorders.frameCode",
     "Parameter-Skript (Strang D): `size` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"addBorders.initCode",
     "Parameter-Skript (Strang D): `size` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"addBorders.size",
     "border width (px)"},
    {"avi.adapt",
     "beat-adaptive: additive on beat window, else 50/50"},
    {"avi.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"avi.filename",
     "as stored in the preset (bare name)"},
    {"avi.persist",
     "beat window length in frames"},
    {"avi.resolvedPath",
     "absolute path (import-time upward search)"},
    {"avi.speedMs",
     "min milliseconds between frame advances"},
    {"bassSpin.beatCode",
     "Parameter-Skript (Strang D): `mode`, `smoothing`, `spinstep`. Klasse A \342\200\224 s. Hinweis bei `DotPlaneParams`."},
    {"bassSpin.colorLeft",
     "Farbe der linken Figur 0x00RRGGBB"},
    {"bassSpin.colorRight",
     "Farbe der rechten Figur 0x00RRGGBB"},
    {"bassSpin.frameCode",
     "Parameter-Skript (Strang D): `mode`, `smoothing`, `spinstep`. Klasse A \342\200\224 s. Hinweis bei `DotPlaneParams`."},
    {"bassSpin.initCode",
     "Parameter-Skript (Strang D): `mode`, `smoothing`, `spinstep`. Klasse A \342\200\224 s. Hinweis bei `DotPlaneParams`."},
    {"bassSpin.left",
     "linke Bildhaelfte (linker Kanal) zeichnen"},
    {"bassSpin.mode",
     "0 lines, 1 filled (approximated as lines)"},
    {"bassSpin.right",
     "rechte Bildhaelfte (rechter Kanal) zeichnen"},
    {"bassSpin.smoothing",
     "Gewicht des neuen Werts: `v = s*neu + (1-s)*alt`"},
    {"bassSpin.spinStep",
     "Drehschritt je Einheit. Vorgabe ist EXAKT der Ausdruck des Originals (`3.14159f/6.0f`), nicht das mathematische pi/6 \342\200\224 die beiden unterscheiden sich in der 7. Stelle, und das summiert sich ueber die Frames in der Drehlage auf."},
    {"blitterFeedback.beatCode",
     "Parameter-Skript (Strang D): `scale`, `scale2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"blitterFeedback.blend",
     "BLEND_AVG mit dem Original statt Replace"},
    {"blitterFeedback.frameCode",
     "Parameter-Skript (Strang D): `scale`, `scale2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"blitterFeedback.initCode",
     "Parameter-Skript (Strang D): `scale`, `scale2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"blitterFeedback.onBeat",
     "Beat setzt fpos = scale2"},
    {"blitterFeedback.scale",
     "Zielwert des fpos-Ease (0..256; 32 = neutral)"},
    {"blitterFeedback.scale2",
     "Beat-Sprungwert (onBeat)"},
    {"blitterFeedback.subpixel",
     "bilineares Sampling (BLEND4)"},
    {"bloom.beatCode",
     "Parameter-Skript (Strang D): `radius`, `intensity`, `threshold`, `vignettestrength` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bloom.downsample",
     "Glow-RT = interne Aufloesung / 2^n (0..4)"},
    {"bloom.frameCode",
     "Parameter-Skript (Strang D): `radius`, `intensity`, `threshold`, `vignettestrength` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bloom.initCode",
     "Parameter-Skript (Strang D): `radius`, `intensity`, `threshold`, `vignettestrength` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bloom.intensity",
     "Faktor des additiven Glow-Anteils"},
    {"bloom.post",
     "true: Glow nur beim Present (kein Feedback)"},
    {"bloom.radius",
     "Gauss-Sigma in Glow-RT-Pixeln (25 Taps fix)"},
    {"bloom.threshold",
     "Helligkeits-Schwelle vor dem Blur (0 = Referenz)"},
    {"bloom.vignette",
     "Abschluss-Multiplikation 1 - r^2 * strength"},
    {"bloom.vignetteStrength",
     "Staerke der Randabdunklung (nur mit `vignette`)"},
    {"blur.beatCode",
     "Parameter-Skript (Strang D): `strength` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"blur.frameCode",
     "Parameter-Skript (Strang D): `strength` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"blur.initCode",
     "Parameter-Skript (Strang D): `strength` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"blur.roundUp",
     "AVS \"round mode\": aus = jeder Teilterm wird abgeschnitten und das Bild klingt bei jeder Anwendung ab; an = fester Ausgleich je Kernel (+4/+5/+3). Vorgabe AUS wie im Original (`roundmode = 0`, r_blur.cpp:75/90) \342\200\224 bis S57 stand hier `true`, und gelesen wurde das Feld ohnehin nirgends."},
    {"blur.strength",
     "1 = light, 2 = medium, 3 = heavy"},
    {"brightness.beatCode",
     "Parameter-Skript (Strang D): `red`, `green`, `blue`, `distance` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"brightness.blue",
     "-4096..4096"},
    {"brightness.color",
     "exclusion color 0x00RRGGBB"},
    {"brightness.distance",
     "exclusion radius 0..255"},
    {"brightness.exclude",
     "leave pixels near `color` untouched"},
    {"brightness.frameCode",
     "Parameter-Skript (Strang D): `red`, `green`, `blue`, `distance` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"brightness.green",
     "-4096..4096"},
    {"brightness.initCode",
     "Parameter-Skript (Strang D): `red`, `green`, `blue`, `distance` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"brightness.red",
     "-4096..4096"},
    {"bufferBlend.beatCode",
     "Parameter-Skript (Strang D): `buffera`, `bufferb`, `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bufferBlend.bufferA",
     "0..7 pool slot, 8 = current frame"},
    {"bufferBlend.bufferB",
     "0..7 pool slot, 8 = current frame"},
    {"bufferBlend.frameCode",
     "Parameter-Skript (Strang D): `buffera`, `bufferb`, `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bufferBlend.initCode",
     "Parameter-Skript (Strang D): `buffera`, `bufferb`, `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bufferBlend.mode",
     "BufferBlendMode 0..10"},
    {"bufferSave.adjustAlpha",
     "Adjustable blend alpha 0..255"},
    {"bufferSave.beatCode",
     "Parameter-Skript (Strang D): `slot`, `dir`, `adjustalpha` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bufferSave.blend",
     "blend mode (applies both directions)"},
    {"bufferSave.dir",
     "Direction (r_stack.cpp): 0 = save, 1 = restore, 2 = alternate starting with save, 3 = alternate starting with restore"},
    {"bufferSave.frameCode",
     "Parameter-Skript (Strang D): `slot`, `dir`, `adjustalpha` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bufferSave.initCode",
     "Parameter-Skript (Strang D): `slot`, `dir`, `adjustalpha` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"bufferSave.slot",
     "global buffer index 0..7"},
    {"bump.beatCode",
     "EEL-Slots. Sie setzen `x`/`y` \342\200\224 die Lichtquelle in 0..1 (mit `oldStyle` in 0..100) \342\200\224 und teilen sich ihre Variablen."},
    {"bump.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"bump.buffern",
     "depth source: 0 = frame, N = global buffer N-1"},
    {"bump.depth",
     "bump strength 0..100"},
    {"bump.depth2",
     "on-beat strength"},
    {"bump.durationFrames",
     "ease-back length"},
    {"bump.frameCode",
     "EEL-Slots. Sie setzen `x`/`y` \342\200\224 die Lichtquelle in 0..1 (mit `oldStyle` in 0..100) \342\200\224 und teilen sich ihre Variablen."},
    {"bump.initCode",
     "EEL-Slots. Sie setzen `x`/`y` \342\200\224 die Lichtquelle in 0..1 (mit `oldStyle` in 0..100) \342\200\224 und teilen sich ihre Variablen."},
    {"bump.invert",
     "invert the depth (luminance)"},
    {"bump.oldStyle",
     "legacy x,y in 0..100 instead of 0..1"},
    {"bump.onBeat",
     "jump to depth2 on beat, ease back"},
    {"camera3d.beatCode",
     "EEL-Slots (Reihenfolge Frame VOR Beat): duerfen `px`..`pz`, `tx`..`tz`, `fov`, `roll`, `fogstart`, `fogend` ueberschreiben. Die Feldwerte oben sind die Startbelegung beim Uebersetzen."},
    {"camera3d.fogColor",
     "0x00RRGGBB (Sprites daempfen nur)"},
    {"camera3d.fogEnd",
     "Distanz, ab der der Nebel voll deckt"},
    {"camera3d.fogStart",
     "Fog-Distanz (Welt); start >= end = aus"},
    {"camera3d.fov",
     "vertikaler Oeffnungswinkel (Grad)"},
    {"camera3d.frameCode",
     "EEL-Slots (Reihenfolge Frame VOR Beat): duerfen `px`..`pz`, `tx`..`tz`, `fov`, `roll`, `fogstart`, `fogend` ueberschreiben. Die Feldwerte oben sind die Startbelegung beim Uebersetzen."},
    {"camera3d.initCode",
     "EEL-Slots (Reihenfolge Frame VOR Beat): duerfen `px`..`pz`, `tx`..`tz`, `fov`, `roll`, `fogstart`, `fogend` ueberschreiben. Die Feldwerte oben sind die Startbelegung beim Uebersetzen."},
    {"camera3d.px",
     "Kamera-Position (Weltkoordinaten)"},
    {"camera3d.py",
     "Kamera-Position, Hochachse (y+ = oben)"},
    {"camera3d.pz",
     "+1/tan(15 deg): Default fuellt [-1,1]"},
    {"camera3d.roll",
     "Drehung um die Blickachse (Grad)"},
    {"camera3d.tx",
     "Blickziel"},
    {"camera3d.ty",
     "Blickziel, Hochachse"},
    {"camera3d.tz",
     "Blickziel, Tiefe (z+ = zum Betrachter)"},
    {"channelShift.beatCode",
     "Parameter-Skript (Strang D): `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"channelShift.frameCode",
     "Parameter-Skript (Strang D): `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"channelShift.initCode",
     "Parameter-Skript (Strang D): `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"channelShift.mode",
     "channel permutation 0..5"},
    {"channelShift.onBeat",
     "random permutation on each beat"},
    {"clear.beatCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"clear.blend",
     "0 = replace, 1 = additive, 2 = 50/50, 3 = current line-blend (r_clear.cpp: blend==1 -> BLEND, blendavg -> BLEND_AVG, blend==2 -> BLEND_LINE)"},
    {"clear.color",
     "0x00RRGGBB"},
    {"clear.frameCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"clear.initCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"clear.onlyFirst",
     "clear only on the first frame"},
    {"colorClip.beatCode",
     "Parameter-Skript (Strang D): `distance` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorClip.clipColor",
     "threshold colour 0x00RRGGBB"},
    {"colorClip.distance",
     "match radius (near mode)"},
    {"colorClip.frameCode",
     "Parameter-Skript (Strang D): `distance` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorClip.initCode",
     "Parameter-Skript (Strang D): `distance` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorClip.mode",
     "1 below, 2 above, 3 near"},
    {"colorClip.outColor",
     "replacement colour"},
    {"colorMap.adjustBlend",
     "ADJUSTABLE weight 0..255"},
    {"colorMap.beatCode",
     "Parameter-Skript (Strang D): `key`, `blendmode`, `adjustblend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorMap.blendMode",
     "0..9 (see above)"},
    {"colorMap.frameCode",
     "Parameter-Skript (Strang D): `key`, `blendmode`, `adjustblend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorMap.initCode",
     "Parameter-Skript (Strang D): `key`, `blendmode`, `adjustblend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorMap.key",
     "input selector 0..5"},
    {"colorMap.stopColor",
     "gradient stop colours 0x00RRGGBB"},
    {"colorMap.stopPos",
     "gradient stop positions 0..255"},
    {"colorModifier.beatCode",
     "EEL-Slots, die sich ihre Variablen mit dem Stufen-Code teilen: init einmal beim Aufbau, frame je Frame, beat je Beat."},
    {"colorModifier.frameCode",
     "EEL-Slots, die sich ihre Variablen mit dem Stufen-Code teilen: init einmal beim Aufbau, frame je Frame, beat je Beat."},
    {"colorModifier.initCode",
     "EEL-Slots, die sich ihre Variablen mit dem Stufen-Code teilen: init einmal beim Aufbau, frame je Frame, beat je Beat."},
    {"colorModifier.levelCode",
     "runs per LUT entry (red/green/blue in/out)"},
    {"colorModifier.recompute",
     "EEL-Slots, die sich ihre Variablen mit dem Stufen-Code teilen: init einmal beim Aufbau, frame je Frame, beat je Beat. Tabelle je Frame neu rechnen statt einmal nach dem Uebersetzen. Noetig, sobald die Kurve von `time` oder vom Audio abhaengt."},
    {"colorReduction.beatCode",
     "Parameter-Skript (Strang D): `levels` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorReduction.frameCode",
     "Parameter-Skript (Strang D): `levels` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorReduction.initCode",
     "Parameter-Skript (Strang D): `levels` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorReduction.levels",
     "bit depth per channel 1..8"},
    {"colorfade.beatCode",
     "Parameter-Skript (Strang D): `faderr`, `faderg`, `faderb`, `beatfaderr`, `beatfaderg`, `beatfaderb`, `onbeatframes` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorfade.beatFaderB",
     "Blau-Schritt im Beat-Fenster (ersetzt `faderB`)"},
    {"colorfade.beatFaderG",
     "Gruen-Schritt im Beat-Fenster (ersetzt `faderG`)"},
    {"colorfade.beatFaderR",
     "Rot-Schritt im Beat-Fenster (ersetzt `faderR`)"},
    {"colorfade.faderB",
     "Blau-Schritt je Frame, -32..32"},
    {"colorfade.faderG",
     "Gruen-Schritt je Frame, -32..32"},
    {"colorfade.faderR",
     "-32..32"},
    {"colorfade.frameCode",
     "Parameter-Skript (Strang D): `faderr`, `faderg`, `faderb`, `beatfaderr`, `beatfaderg`, `beatfaderb`, `onbeatframes` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorfade.initCode",
     "Parameter-Skript (Strang D): `faderr`, `faderg`, `faderb`, `beatfaderr`, `beatfaderg`, `beatfaderb`, `onbeatframes` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"colorfade.onBeatFrames",
     "LumiViz-ERWEITERUNG (Vorschlag Patrik): wie viele Frames der Beat-Zustand gehalten wird, bevor `slowFade` ihn zurueckzieht. Das Original kennt kein Fenster \342\200\224 es setzt die Fader im Beat-Frame und zieht ab dem naechsten zurueck. **Die Vorgabe 1 ist deshalb genau dieses Verhalten**, ein importiertes AVS-Preset aendert sich also nicht; groessere Werte sind die neue Moeglichkeit. Ohne `slowFade` wirkt das Feld nicht \342\200\224 dann gibt es keinen Beat-Zustand, den man halten koennte."},
    {"colorfade.onBeatRandom",
     "`enabled`-Bit 1 von `r_colorfade`: im Beat-Frame werden die Fader ZUFAELLIG gewaehlt statt aus `beatFader*` genommen \342\200\224 Rot und Blau aus `rand()%32 - 6`, Gruen aus `rand()%64 - 32`, wobei Werte mit Betrag unter 16 auf +-32 aufgerissen werden (r_colorfade.cpp:157-161)."},
    {"colorfade.slowFade",
     "`enabled`-Bit 2 von `r_colorfade`: die Fader wandern um EINEN Schritt je Frame auf ihren Zielwert zu, statt sofort dort zu stehen. Nur mit diesem Bit wirken die Beat-Fader ueberhaupt \342\200\224 im Original ist der Beat-Zweig sonst gar nicht erreichbar (`if (!(enabled&4)) \342\200\246 else if (isBeat) \342\200\246`)."},
    {"comment.text",
     "Freier Text. Der Knoten zeichnet nichts \342\200\224 er haelt eine Notiz in der Kette fest."},
    {"convolution.absolute",
     "Betrag des Ergebnisses nehmen \342\200\224 negative Summen werden gespiegelt statt auf 0 geklemmt (macht Kanten-Kerne beidseitig sichtbar)."},
    {"convolution.beatCode",
     "Parameter-Skript (Strang D): `bias`, `scale`, `edgemode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"convolution.bias",
     "Festwert, der nach der Division auf jeden Kanal addiert wird."},
    {"convolution.edgeMode",
     "0 extend, 1 wrap"},
    {"convolution.frameCode",
     "Parameter-Skript (Strang D): `bias`, `scale`, `edgemode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"convolution.initCode",
     "Parameter-Skript (Strang D): `bias`, `scale`, `edgemode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"convolution.kernel",
     "identity (center=1)"},
    {"convolution.scale",
     "Teiler der gewichteten Summe (0 wird als 1 gerechnet). Die Summe der Kernwerte hier einzutragen haelt die Helligkeit."},
    {"convolution.twoPass",
     "Den Kern zweimal hintereinander anwenden."},
    {"customBpm.arbitrary",
     "emit a beat every `arbitraryMs`"},
    {"customBpm.arbitraryMs",
     "interval for arbitrary mode"},
    {"customBpm.beatCode",
     "Parameter-Skript (Strang D): `arbitraryms`, `skipcount`, `skipfirst` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"customBpm.frameCode",
     "Parameter-Skript (Strang D): `arbitraryms`, `skipcount`, `skipfirst` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"customBpm.initCode",
     "Parameter-Skript (Strang D): `arbitraryms`, `skipcount`, `skipfirst` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"customBpm.invert",
     "invert the (possibly modified) beat"},
    {"customBpm.skip",
     "only pass every (skipCount+1)-th beat"},
    {"customBpm.skipCount",
     "Rohwert `skipVal` der Referenz: durchgelassen wird jeder (skipCount+1)-te Beat, 0 heisst also \"jeden\"."},
    {"customBpm.skipFirst",
     "`skipfirst`: die ersten N Beats des Presets werden verschluckt, und der Skip-Zaehler laeuft waehrenddessen NICHT mit (r_bpm.cpp:148 kehrt vor dem Skip-Block zurueck)."},
    {"debugBars.color",
     "0x00RRGGBB"},
    {"debugBars.orbitSpeed",
     "revolutions factor (1 = one turn per ~6.3 s)"},
    {"domainWarp.beatCode",
     "EEL, on beat"},
    {"domainWarp.blend",
     "0 replace, 1 additive, 2 50/50 over the current image"},
    {"domainWarp.colorCycle",
     "LUT offset advance per second"},
    {"domainWarp.colorScale",
     "field\342\206\222LUT position factor"},
    {"domainWarp.frameCode",
     "EEL, per frame (audio-reactive field)"},
    {"domainWarp.gain",
     "amplitude falloff per octave"},
    {"domainWarp.gradientPreset",
     "ColorGradientModule palette"},
    {"domainWarp.initCode",
     "EEL, once"},
    {"domainWarp.lacunarity",
     "frequency multiplier per octave"},
    {"domainWarp.octaves",
     "fBm octave count (1..10)"},
    {"domainWarp.offsetX",
     "pan (x)"},
    {"domainWarp.offsetY",
     "pan (y)"},
    {"domainWarp.scale",
     "base spatial frequency"},
    {"domainWarp.speed",
     "time-evolution speed"},
    {"domainWarp.warp",
     "domain-warp strength"},
    {"domainWarp.warpScale",
     "warp-field frequency relative to base"},
    {"dotFountain.angle",
     "Neigung der Ansicht in Grad."},
    {"dotFountain.beatCode",
     "Parameter-Skript (Strang D): `rotvel`, `angle` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"dotFountain.colors",
     "Fuenf Stuetzstellen des Farbverlaufs (0x00RRGGBB), ueber die Hoehe der Teilchen abgebildet."},
    {"dotFountain.frameCode",
     "Parameter-Skript (Strang D): `rotvel`, `angle` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"dotFountain.initCode",
     "Parameter-Skript (Strang D): `rotvel`, `angle` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"dotFountain.rotVel",
     "Drehgeschwindigkeit (Vorzeichen = Richtung)."},
    {"dotFountain.startRotation",
     "Start-Drehwinkel in Grad \342\200\224 wie Dot Plane speichert das Original seine laufende Rotation im Preset (`r = rr/32`, r_dotfnt load_config)."},
    {"dotGrid.beatCode",
     "Parameter-Skript (Strang D): `spacing`, `xmove`, `ymove`, `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"dotGrid.blend",
     "0 replace, 1 additive, 2 50/50, 3 BLEND_LINE (SRM-Zustand, r_dotgrid.cpp:151-159, S3)"},
    {"dotGrid.colors",
     "Farbtafel (0x00RRGGBB). Mehrere Eintraege werden ueber die Frames durchgeschaltet, wie die AVS-Farbtabelle."},
    {"dotGrid.frameCode",
     "Parameter-Skript (Strang D): `spacing`, `xmove`, `ymove`, `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"dotGrid.initCode",
     "Parameter-Skript (Strang D): `spacing`, `xmove`, `ymove`, `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"dotGrid.spacing",
     "grid spacing (px)"},
    {"dotGrid.xMove",
     "horizontal scroll (fixed-point /256 per frame)"},
    {"dotGrid.yMove",
     "vertical scroll"},
    {"dotPlane.angle",
     "viewing tilt angle"},
    {"dotPlane.beatCode",
     "Parameter-Skript (Strang D): `rotvel`, `angle`, `camdistance`, `settle`. ACHTUNG Klasse A \342\200\224 ein Skript hier verlaesst die Referenz; der Editor sagt das an, weil die \342\232\240 an den Reglern nur feste Werte pruefen kann."},
    {"dotPlane.camDistance",
     "matrixTranslate z (Original 400)"},
    {"dotPlane.colors",
     "Fuenf Stuetzstellen des Farbverlaufs (0x00RRGGBB), ueber die Hoehe der Gitterpunkte abgebildet."},
    {"dotPlane.frameCode",
     "Parameter-Skript (Strang D): `rotvel`, `angle`, `camdistance`, `settle`. ACHTUNG Klasse A \342\200\224 ein Skript hier verlaesst die Referenz; der Editor sagt das an, weil die \342\232\240 an den Reglern nur feste Werte pruefen kann."},
    {"dotPlane.initCode",
     "Parameter-Skript (Strang D): `rotvel`, `angle`, `camdistance`, `settle`. ACHTUNG Klasse A \342\200\224 ein Skript hier verlaesst die Referenz; der Editor sagt das an, weil die \342\232\240 an den Reglern nur feste Werte pruefen kann."},
    {"dotPlane.rotVel",
     "rotation speed (-50..50 in AVS)"},
    {"dotPlane.settle",
     "Absinken je Frame: `vel -= settle*h/255`"},
    {"dotPlane.startRotation",
     "Start-Drehwinkel in Grad \342\200\224 das Original SPEICHERT seine laufende Rotation im Preset (`r = rr/32`, r_dotpln load_config) und steht damit beim Laden sofort in der gespeicherten Stellung (Tie Tunnel: 44,84\302\260)."},
    {"dynamicDistanceModifier.beatCode",
     "Skript-Variablen: **nur `d`** (+ `b` und der Audio-Satz)."},
    {"dynamicDistanceModifier.blend",
     "50/50 with the original image"},
    {"dynamicDistanceModifier.frameCode",
     "Skript-Variablen: **nur `d`** (+ `b` und der Audio-Satz)."},
    {"dynamicDistanceModifier.initCode",
     "Skript-Variablen: **nur `d`** (+ `b` und der Audio-Satz)."},
    {"dynamicDistanceModifier.pixelCode",
     "Skript-Variablen: **nur `d`** (+ `b` und der Audio-Satz)."},
    {"dynamicDistanceModifier.subpixel",
     "Zwischenwerte beim Abtasten (AVS `subpixel`, r_ddm.cpp:313 / r_shift.cpp:206)."},
    {"dynamicMovement.beatCode",
     "EEL-Quartett. Der Punkt-Code laeuft je Gitterknoten und schreibt `x`/`y` (kartesisch) bzw. `d`/`r` (polar) und `alpha`; init/frame/beat laufen einmal je Aufbau/Frame/Beat und teilen sich die Variablen."},
    {"dynamicMovement.blend",
     "r_dmove flags: `blend` mixes the moved pixel onto the original by the script's per-cell alpha; `nomove` skips displacement and only alpha-fades."},
    {"dynamicMovement.buffern",
     "Source image: 0 = current frame, 1..8 = global buffer (r_dmove fbin; missing buffer -> effect is a passthrough, r_dmove.cpp:290)"},
    {"dynamicMovement.frameCode",
     "EEL-Quartett. Der Punkt-Code laeuft je Gitterknoten und schreibt `x`/`y` (kartesisch) bzw. `d`/`r` (polar) und `alpha`; init/frame/beat laufen einmal je Aufbau/Frame/Beat und teilen sich die Variablen."},
    {"dynamicMovement.initCode",
     "EEL-Quartett. Der Punkt-Code laeuft je Gitterknoten und schreibt `x`/`y` (kartesisch) bzw. `d`/`r` (polar) und `alpha`; init/frame/beat laufen einmal je Aufbau/Frame/Beat und teilen sich die Variablen."},
    {"dynamicMovement.nomove",
     "Nicht verschieben \342\200\224 nur das `alpha` des Skripts wirkt (Ueberblenden ohne Bewegung, r_dmove-Flag)."},
    {"dynamicMovement.pointCode",
     "EEL-Quartett. Der Punkt-Code laeuft je Gitterknoten und schreibt `x`/`y` (kartesisch) bzw. `d`/`r` (polar) und `alpha`; init/frame/beat laufen einmal je Aufbau/Frame/Beat und teilen sich die Variablen. Laeuft je Gitterknoten: gelesen werden `x`, `y`, `d`, `r`, `alpha` \342\200\224 wo der Bildpunkt seine Farbe HERholt, nicht wohin er geht."},
    {"dynamicMovement.rectCoords",
     "Punkt-Code rechnet in Bildpunkten statt in normierten Koordinaten."},
    {"dynamicMovement.subpixel",
     "bilinear (on) vs nearest (off) source sampling"},
    {"dynamicMovement.wrap",
     "Was ueber den Rand hinauszeigt, kommt auf der Gegenseite wieder herein (aus statt dessen: der Rand wird festgehalten)."},
    {"dynamicMovement.xres",
     "EEL-Quartett. Der Punkt-Code laeuft je Gitterknoten und schreibt `x`/`y` (kartesisch) bzw. `d`/`r` (polar) und `alpha`; init/frame/beat laufen einmal je Aufbau/Frame/Beat und teilen sich die Variablen. Laeuft je Gitterknoten: gelesen werden `x`, `y`, `d`, `r`, `alpha` \342\200\224 wo der Bildpunkt seine Farbe HERholt, nicht wohin er geht. Gitterknoten waagrecht. Grober heisst weicher (dazwischen wird interpoliert) und schneller."},
    {"dynamicMovement.yres",
     "Gitterknoten senkrecht."},
    {"dynamicShift.beatCode",
     "EEL-Slots. Sie setzen `x`/`y` \342\200\224 die Verschiebung des ganzen Bildes \342\200\224 und teilen sich ihre Variablen."},
    {"dynamicShift.blend",
     "50/50 with the original image"},
    {"dynamicShift.frameCode",
     "EEL-Slots. Sie setzen `x`/`y` \342\200\224 die Verschiebung des ganzen Bildes \342\200\224 und teilen sich ihre Variablen."},
    {"dynamicShift.initCode",
     "EEL-Slots. Sie setzen `x`/`y` \342\200\224 die Verschiebung des ganzen Bildes \342\200\224 und teilen sich ihre Variablen."},
    {"dynamicShift.subpixel",
     "Zwischenwerte beim Abtasten (AVS `subpixel`, r_ddm.cpp:313 / r_shift.cpp:206)."},
    {"fadeout.beatCode",
     "Parameter-Skript (Strang D): `fadelen` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"fadeout.color",
     "target color 0x00RRGGBB"},
    {"fadeout.fadeLen",
     "per-frame step 0..92 (AVS range)"},
    {"fadeout.frameCode",
     "Parameter-Skript (Strang D): `fadelen` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"fadeout.initCode",
     "Parameter-Skript (Strang D): `fadelen` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"fastBrightness.beatCode",
     "Parameter-Skript (Strang D): `dir` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"fastBrightness.dir",
     "0..2"},
    {"fastBrightness.frameCode",
     "Parameter-Skript (Strang D): `dir` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"fastBrightness.initCode",
     "Parameter-Skript (Strang D): `dir` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"flame.beatCode",
     "Parameter-Skript (Strang D): die Variationsbeiwerte und `rotation` + Audio-Satz. Leer = kein Skript."},
    {"flame.blend",
     "0 ersetzen, 1 additiv, 2 50/50."},
    {"flame.dotSize",
     "Punktdurchmesser in Pixeln."},
    {"flame.frameCode",
     "Parameter-Skript (Strang D): die Variationsbeiwerte und `rotation` + Audio-Satz. Leer = kein Skript."},
    {"flame.functions",
     "affine map count (2..4)"},
    {"flame.gradientPreset",
     "Name des Farbverlaufs \342\200\224 die Punkte werden ueber ihre Nummer im Zug eingefaerbt."},
    {"flame.initCode",
     "Parameter-Skript (Strang D): die Variationsbeiwerte und `rotation` + Audio-Satz. Leer = kein Skript."},
    {"flame.points",
     "Zuege des Chaosspiels je Frame \342\200\224 mehr heisst ein dichteres Bild, nicht ein anderes."},
    {"flame.rotation",
     "Fester Drehwinkel in Radiant, addiert zur laufenden Drehung."},
    {"flame.rotationSpeed",
     "Laufende Drehung in Radiant je Sekunde (0 = steht still)."},
    {"flame.scale",
     "Groesse der Figur im Bild (Faktor auf die Koordinaten, vor der Drehung)."},
    {"flame.variation",
     "0 linear 1 sinusoidal 2 spherical 3 swirl 4 horseshoe"},
    {"fractal2D.beatCode",
     "EEL, on beat"},
    {"fractal2D.blend",
     "0 replace, 1 additive, 2 50/50 over the current image"},
    {"fractal2D.centerX",
     "view centre (real part)"},
    {"fractal2D.centerY",
     "view centre (imag part)"},
    {"fractal2D.colorCycle",
     "LUT offset advance per second (palette drift)"},
    {"fractal2D.colorScale",
     "iteration\342\206\222LUT position factor"},
    {"fractal2D.escapeR",
     "escape radius (|z|^2 threshold)"},
    {"fractal2D.frameCode",
     "EEL, per frame (audio-reactive view)"},
    {"fractal2D.ftype",
     "0 Mandelbrot 1 Julia 2 Burning Ship 3 Tricorn"},
    {"fractal2D.gradientPreset",
     "ColorGradientModule palette name"},
    {"fractal2D.initCode",
     "EEL, once (seed cx,cy,zoom,\342\200\246)"},
    {"fractal2D.insideColor",
     "colour of the non-escaping set (0x00RRGGBB)"},
    {"fractal2D.juliaX",
     "Julia / Phoenix seed (real)"},
    {"fractal2D.juliaY",
     "Julia / Phoenix seed (imag)"},
    {"fractal2D.maxIter",
     "escape-time iteration cap"},
    {"fractal2D.power",
     "Multibrot / Nova exponent"},
    {"fractal2D.rotation",
     "view rotation (radians)"},
    {"fractal2D.smooth",
     "continuous (fractional) iteration colouring"},
    {"fractal2D.zoom",
     "view scale (>1 magnifies)"},
    {"fractal3D.ambient",
     "ambient floor"},
    {"fractal3D.ao",
     "cheap ambient occlusion"},
    {"fractal3D.background",
     "miss colour (0x00RRGGBB)"},
    {"fractal3D.beatCode",
     "Parameter-Skript (Strang D): `yaw`, `pitch`, `dist`, `power`, `scale`, `fold` + Audio-Satz \342\200\224 Kamera und Form live. Leer = kein Skript."},
    {"fractal3D.blend",
     "Auf das bestehende Bild: 0 ersetzen, 1 additiv (geklemmt), 2 50/50."},
    {"fractal3D.colorCycle",
     "Vorschub der Farbphase je Sekunde (0 = stehende Farben)."},
    {"fractal3D.colorScale",
     "Faerbung: Farbtafel-Index = `fract(Trefferwert * colorScale + Phase)`."},
    {"fractal3D.dist",
     "camera distance from origin"},
    {"fractal3D.fold",
     "Mandelbox fold limit"},
    {"fractal3D.fov",
     "field-of-view scale"},
    {"fractal3D.frameCode",
     "Parameter-Skript (Strang D): `yaw`, `pitch`, `dist`, `power`, `scale`, `fold` + Audio-Satz \342\200\224 Kamera und Form live. Leer = kein Skript."},
    {"fractal3D.ftype",
     "0 Mandelbulb 1 Mandelbox 2 Menger 3 Quaternion-Julia 4 KIFS"},
    {"fractal3D.gradientPreset",
     "Name des Farbverlaufs, ueber den die Oberflaeche eingefaerbt wird."},
    {"fractal3D.initCode",
     "Parameter-Skript (Strang D): `yaw`, `pitch`, `dist`, `power`, `scale`, `fold` + Audio-Satz \342\200\224 Kamera und Form live. Leer = kein Skript."},
    {"fractal3D.juliaW",
     "Quaternion-Julia-Konstante, vierte Komponente \342\200\224 nur bei `type = 3`."},
    {"fractal3D.juliaX",
     "Quaternion-Julia seed"},
    {"fractal3D.juliaY",
     "Quaternion-Julia-Konstante, zweite Komponente \342\200\224 nur bei `type = 3`."},
    {"fractal3D.juliaZ",
     "Quaternion-Julia-Konstante, dritte Komponente \342\200\224 nur bei `type = 3`."},
    {"fractal3D.lightPitch",
     "key-light direction (elevation)"},
    {"fractal3D.lightYaw",
     "key-light direction (azimuth)"},
    {"fractal3D.maxIter",
     "DE iteration count"},
    {"fractal3D.maxSteps",
     "raymarch step cap"},
    {"fractal3D.pitch",
     "camera orbit elevation (radians)"},
    {"fractal3D.power",
     "Mandelbulb exponent"},
    {"fractal3D.scale",
     "Mandelbox / KIFS scale"},
    {"fractal3D.yaw",
     "camera orbit azimuth (radians)"},
    {"fractalZoomer.beatCode",
     "Parameter-Skript (Strang D): `centerX`, `centerY`, `zoomSpeed`, `rotationSpeed` + Audio-Satz. Leer = kein Skript."},
    {"fractalZoomer.centerX",
     "zoom target (a classic Misiurewicz point)"},
    {"fractalZoomer.centerY",
     "Zoomziel, Imaginaerteil (Gegenstueck zu `centerX`)."},
    {"fractalZoomer.colorCycle",
     "Vorschub der Farbphase je Sekunde (0 = stehende Farben)."},
    {"fractalZoomer.colorScale",
     "Faerbung: Farbtafel-Index = `fract(iterationen * colorScale + Phase)`. Groesser heisst engere Farbringe."},
    {"fractalZoomer.feedback",
     "Anteil des vorigen Bildes, der stehen bleibt: 0 = keine Schleife, 0,5 = 50/50, 1 = Standbild. Seit S57 eine echte STAERKE \342\200\224 vorher las der Shader das Feld nur als Schalter (`> 0,01 ? 50/50 : ersetzen`), und 0,3 wie 1,0 ergaben dasselbe Bild."},
    {"fractalZoomer.frameCode",
     "Parameter-Skript (Strang D): `centerX`, `centerY`, `zoomSpeed`, `rotationSpeed` + Audio-Satz. Leer = kein Skript."},
    {"fractalZoomer.ftype",
     "0 Mandelbrot 1 Julia 2 Burning Ship"},
    {"fractalZoomer.gradientPreset",
     "Name des Farbverlaufs, ueber den die Iterationszahl abgebildet wird."},
    {"fractalZoomer.initCode",
     "Parameter-Skript (Strang D): `centerX`, `centerY`, `zoomSpeed`, `rotationSpeed` + Audio-Satz. Leer = kein Skript."},
    {"fractalZoomer.insideColor",
     "Farbe der Punkte, die nicht entkommen (das Innere der Menge), 0x00RRGGBB."},
    {"fractalZoomer.juliaX",
     "Julia-Konstante, Realteil \342\200\224 wirkt nur bei `type = 1`."},
    {"fractalZoomer.juliaY",
     "Julia-Konstante, Imaginaerteil \342\200\224 wirkt nur bei `type = 1`."},
    {"fractalZoomer.maxIter",
     "Obergrenze der Iterationen je Pixel. Hoeher heisst mehr Struktur tief im Zoom, aber auch mehr Rechenzeit je Frame."},
    {"fractalZoomer.rotationSpeed",
     "radians per frame"},
    {"fractalZoomer.zoomSpeed",
     "per-frame zoom factor (>1 zooms in)"},
    {"fyrewurx.beatCode",
     "Parameter-Skript (Strang D): `sparks`, `speed`, `gravity`, `life`, `dotsize`, `huedrift`, `burstspread` + `b`/`w`/`h` + Audio-Satz."},
    {"fyrewurx.burstSpread",
     "Faktor auf die Streuung der Burst-Mitte"},
    {"fyrewurx.dotSize",
     "Funkengroesse in Pixeln (war fest 2)"},
    {"fyrewurx.frameCode",
     "Parameter-Skript (Strang D): `sparks`, `speed`, `gravity`, `life`, `dotsize`, `huedrift`, `burstspread` + `b`/`w`/`h` + Audio-Satz."},
    {"fyrewurx.gravity",
     "downward pull (NDC/s^2)"},
    {"fyrewurx.hueDrift",
     "Farbstreuung je Funke (war fest 0,6)"},
    {"fyrewurx.initCode",
     "Parameter-Skript (Strang D): `sparks`, `speed`, `gravity`, `life`, `dotsize`, `huedrift`, `burstspread` + `b`/`w`/`h` + Audio-Satz."},
    {"fyrewurx.lifeSeconds",
     "spark lifetime"},
    {"fyrewurx.sparks",
     "sparks per burst"},
    {"fyrewurx.speed",
     "initial spark speed scale (NDC/s)"},
    {"glowOrbs.beatCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Zahl der Orbs); der Punkt-Code laeuft je Orb."},
    {"glowOrbs.falloff",
     "Halo-Profil k in exp(-r^2*k)"},
    {"glowOrbs.frameCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Zahl der Orbs); der Punkt-Code laeuft je Orb."},
    {"glowOrbs.haloIntensity",
     "Halo-Helligkeit (0 = aus)"},
    {"glowOrbs.haloScale",
     "Halo-Radius = radius * haloScale"},
    {"glowOrbs.initCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Zahl der Orbs); der Punkt-Code laeuft je Orb."},
    {"glowOrbs.orbCount",
     "Default-n (Skript-n ueberschreibt)"},
    {"glowOrbs.pointCode",
     "je Orb (i = Orb-Index)"},
    {"grain.amount",
     "gated pixel fraction 0..100 (smax)"},
    {"grain.beatCode",
     "Parameter-Skript (Strang D): `amount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"grain.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"grain.frameCode",
     "Parameter-Skript (Strang D): `amount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"grain.initCode",
     "Parameter-Skript (Strang D): `amount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"grain.staticGrain",
     "frozen noise vs. per-frame shimmer"},
    {"hostgroup.blendOut",
     "Gruppen-Buffer -> Parent"},
    {"hostgroup.crossfadeSeconds",
     "Blend-Dauer beim Gruppen-Wechsel"},
    {"hostgroup.curveIn",
     "0 = linear (weitere Kurven mit HG2)"},
    {"hostgroup.curveOut",
     "0 = linear"},
    {"hostgroup.outAdjustAlpha",
     "Adjustable out-alpha 0..255"},
    {"importNotes.text",
     "Bericht des Importeurs (nur lesen): was am Preset nicht uebernommen werden konnte."},
    {"interferences.alpha",
     "per-copy weight 0..255"},
    {"interferences.alpha2",
     "on-beat target alpha"},
    {"interferences.beatCode",
     "Parameter-Skript (Strang D): `points`, `distance`, `alpha`, `rotation`, `rotationinc`, `speed` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"interferences.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"interferences.distance",
     "copy offset radius (px)"},
    {"interferences.distance2",
     "on-beat target distance"},
    {"interferences.frameCode",
     "Parameter-Skript (Strang D): `points`, `distance`, `alpha`, `rotation`, `rotationinc`, `speed` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"interferences.initCode",
     "Parameter-Skript (Strang D): `points`, `distance`, `alpha`, `rotation`, `rotationinc`, `speed` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"interferences.onBeat",
     "morph to the *2 set on a beat"},
    {"interferences.points",
     "number of copies 1..8"},
    {"interferences.rgb",
     "split copies across channels"},
    {"interferences.rotation",
     "initial rotation 0..255 (of a full turn)"},
    {"interferences.rotationInc",
     "rotation delta per frame"},
    {"interferences.rotationInc2",
     "on-beat target rotation delta"},
    {"interferences.speed",
     "beat-morph transition speed"},
    {"interleave.beatCode",
     "Parameter-Skript (Strang D): `x`, `y`, `x2`, `y2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"interleave.beatDuration",
     "ease length"},
    {"interleave.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"interleave.color",
     "stripe colour 0x00RRGGBB"},
    {"interleave.frameCode",
     "Parameter-Skript (Strang D): `x`, `y`, `x2`, `y2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"interleave.initCode",
     "Parameter-Skript (Strang D): `x`, `y`, `x2`, `y2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"interleave.onBeat",
     "ease to x2/y2 on beat"},
    {"interleave.x",
     "horizontal stripe spacing (px, 0 = off)"},
    {"interleave.x2",
     "Ziel-Abstand waagrecht im Beat-Uebergang"},
    {"interleave.y",
     "vertical stripe spacing (px, 0 = off)"},
    {"interleave.y2",
     "Ziel-Abstand senkrecht im Beat-Uebergang"},
    {"jherikoGlobal.beatCode",
     "EEL-Slots ohne eigenes Bild: der Knoten rechnet nur und legt seine Ergebnisse in den geteilten Variablen (`reg00`..`reg99`, `gmegabuf`) ab, aus denen die folgenden Knoten lesen. `loadMode` steuert, wann der Init-Slot erneut laeuft."},
    {"jherikoGlobal.frameCode",
     "EEL-Slots ohne eigenes Bild: der Knoten rechnet nur und legt seine Ergebnisse in den geteilten Variablen (`reg00`..`reg99`, `gmegabuf`) ab, aus denen die folgenden Knoten lesen. `loadMode` steuert, wann der Init-Slot erneut laeuft."},
    {"jherikoGlobal.initCode",
     "EEL-Slots ohne eigenes Bild: der Knoten rechnet nur und legt seine Ergebnisse in den geteilten Variablen (`reg00`..`reg99`, `gmegabuf`) ab, aus denen die folgenden Knoten lesen. `loadMode` steuert, wann der Init-Slot erneut laeuft."},
    {"jherikoGlobal.loadMode",
     "0 none, 1 once, 2 code-control, 3 every-frame"},
    {"kleinian.beatCode",
     "Parameter-Skript (Strang D): `p`, `q` (als Zahlen), `morph`, `zoom`, `rotation` + Audio-Satz. Leer = kein Skript."},
    {"kleinian.blend",
     "Auf das bestehende Bild: 0 ersetzen, 1 additiv (geklemmt), 2 50/50."},
    {"kleinian.colorCycle",
     "Vorschub der Farbphase je Sekunde (0 = stehende Farben)."},
    {"kleinian.colorScale",
     "Faerbung: Farbtafel-Index = `fract(Spiegelungszahl * colorScale + Phase)`."},
    {"kleinian.frameCode",
     "Parameter-Skript (Strang D): `p`, `q` (als Zahlen), `morph`, `zoom`, `rotation` + Audio-Satz. Leer = kein Skript."},
    {"kleinian.gradientPreset",
     "Name des Farbverlaufs, ueber den die Spiegelungszahl abgebildet wird."},
    {"kleinian.initCode",
     "Parameter-Skript (Strang D): `p`, `q` (als Zahlen), `morph`, `zoom`, `rotation` + Audio-Satz. Leer = kein Skript."},
    {"kleinian.iterations",
     "inversion iteration cap"},
    {"kleinian.morph",
     "tiling morph phase"},
    {"kleinian.p",
     "polygon sides"},
    {"kleinian.q",
     "polygons per vertex (1/p + 1/q < 1/2 \342\206\222 hyperbolic)"},
    {"kleinian.rotation",
     "Drehung der Kachelung in Radiant."},
    {"kleinian.zoom",
     "Ausschnitt der Poincar\303\251-Scheibe (groesser = naeher heran)."},
    {"list.blendIn",
     "parent -> list buffer"},
    {"list.blendOut",
     "list buffer -> parent"},
    {"list.bufferIn",
     "pool slot for Buffer in-blend"},
    {"list.bufferInInvert",
     "invert in-blend buffer depth"},
    {"list.bufferOut",
     "pool slot for Buffer out-blend"},
    {"list.bufferOutInvert",
     "invert out-blend buffer depth"},
    {"list.clearEveryFrame",
     "clear the list buffer at frame start"},
    {"list.frameCode",
     "EEL, per frame (enabled/clear/beat/alphain/alphaout)"},
    {"list.inAdjustAlpha",
     "Adjustable in-alpha 0..255"},
    {"list.initCode",
     "EEL, once after (re)compile"},
    {"list.onBeatFrames",
     "N (>= 1)"},
    {"list.onBeatRender",
     "render only for N frames after a beat"},
    {"list.outAdjustAlpha",
     "Adjustable out-alpha 0..255"},
    {"list.useCode",
     "run the EEL list slots"},
    {"lyapunov.aMax",
     "Rechte Kante des Ausschnitts auf der a-Achse."},
    {"lyapunov.aMin",
     "view rectangle (a axis)"},
    {"lyapunov.bMax",
     "Obere Kante des Ausschnitts auf der b-Achse."},
    {"lyapunov.bMin",
     "view rectangle (b axis)"},
    {"lyapunov.beatCode",
     "Parameter-Skript (Strang D): `aMin`, `aMax`, `bMin`, `bMax` \342\200\224 der Ausschnitt \342\200\224 + Audio-Satz. Leer = kein Skript."},
    {"lyapunov.blend",
     "Auf das bestehende Bild: 0 ersetzen, 1 additiv (geklemmt), 2 50/50."},
    {"lyapunov.colorCycle",
     "Vorschub der Farbphase je Sekunde (0 = stehende Farben)."},
    {"lyapunov.colorScale",
     "Faerbung: Farbtafel-Index = `fract(Lyapunov-Exponent * colorScale + Phase)`. Gilt nur fuer die chaotischen Zonen; die geordneten bekommen `negColor`."},
    {"lyapunov.frameCode",
     "Parameter-Skript (Strang D): `aMin`, `aMax`, `bMin`, `bMax` \342\200\224 der Ausschnitt \342\200\224 + Audio-Satz. Leer = kein Skript."},
    {"lyapunov.gradientPreset",
     "Name des Farbverlaufs fuer die chaotischen Zonen."},
    {"lyapunov.initCode",
     "Parameter-Skript (Strang D): `aMin`, `aMax`, `bMin`, `bMax` \342\200\224 der Ausschnitt \342\200\224 + Audio-Satz. Leer = kein Skript."},
    {"lyapunov.iterations",
     "measured iterations"},
    {"lyapunov.negColor",
     "ordered-zone colour (negative exponent)"},
    {"lyapunov.sequence",
     "a/b pattern (A/B chars; others ignored)"},
    {"lyapunov.warmup",
     "settle iterations before measuring"},
    {"meshWarp.beatCode",
     "Parameter-Skript (Strang D): `gridx`, `gridy`, `mixamount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript. Parameter-Skript (Strang D): `gridx`, `gridy`, `mixamount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript. Parameter-Skript (Strang D): `gridx`, `gridy`, `mixamount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"meshWarp.code",
     "GLSL: definiert `vec2 warp(vec2 uv)` (uv 0..1, R\303\274ckgabe = Quell-UV). Uniforms: uTime, uDelta, uFrame, uResolution, bass, mid, treb, vol, beat. Leer = Identit\303\244t (Passthrough)"},
    {"meshWarp.frameCode",
     "Parameter-Skript (Strang D): `gridx`, `gridy`, `mixamount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript. Parameter-Skript (Strang D): `gridx`, `gridy`, `mixamount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"meshWarp.gridX",
     "Gitter-Quads in X (2..256) \342\200\224 GPU-Vertex-Arbeit, hohe Werte kosten kaum; grob = kantiger Warp"},
    {"meshWarp.gridY",
     "Gitter-Quads in Y (2..192)"},
    {"meshWarp.initCode",
     "Parameter-Skript (Strang D): `gridx`, `gridy`, `mixamount` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"meshWarp.mixAmount",
     "Anteil des gewarpten Bilds 0..1 (1 = ersetzen; darunter Mix mit der ungewarpten Abtastung)"},
    {"meshWarp.wrapUv",
     "Quell-UV au\303\237erhalb 0..1: an = wiederholen (fract), aus = Randpixel klemmen"},
    {"metaballs3d.beatCode",
     "Parameter-Skript (Strang D): `count`, `radius`, `speed`, `threshold`, `spread`, `depth`, `phase` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"metaballs3d.blend",
     "0 replace, 1 additiv, 2 50/50 \342\200\224 die Referenz zeichnet DECKENDE Koerper (Sichtvergleich S52), deshalb Replace als Vorgabe."},
    {"metaballs3d.colors",
     "Palette (0x00RRGGBB). NICHT leer: der Leser heilt eine leere Tafel auf Weiss, eine leere liesse sich also gar nicht speichern (Roundtrip-Befund S56). Die Vorgabe sagt es deshalb selbst."},
    {"metaballs3d.count",
     "Zahl der Kugeln (1..16)"},
    {"metaballs3d.depth",
     "Kamera-Abstand der Bahnmitte (war fest 1,2)"},
    {"metaballs3d.frameCode",
     "Parameter-Skript (Strang D): `count`, `radius`, `speed`, `threshold`, `spread`, `depth`, `phase` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"metaballs3d.initCode",
     "Parameter-Skript (Strang D): `count`, `radius`, `speed`, `threshold`, `spread`, `depth`, `phase` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"metaballs3d.phase",
     "Phasenversatz je Kugel (war fest 1,7)"},
    {"metaballs3d.radius",
     "Radius-Skala je Kugel (NDC) \342\200\224 sichtkalibriert gegen die echte APE (S52): 0,30 deckte deutlich mehr Flaeche als die Referenz."},
    {"metaballs3d.speed",
     "Bahngeschwindigkeit"},
    {"metaballs3d.spread",
     "Faktor auf die Bahnweite (war fest 1)"},
    {"metaballs3d.threshold",
     "Isowert der Oberflaeche"},
    {"milkdrop.debugGrid",
     "calibration overlay AFTER the composite"},
    {"milkdrop.meshX",
     "warp mesh (app setting in the original, no preset key)"},
    {"milkdrop.meshY",
     "Warp-Gitter senkrecht (Original-Vorgabe 24; hoeher = feinerer Warp)."},
    {"milkdrop.preset",
     "translated .milk incl. HLSL texts"},
    {"milkdrop.presetDir",
     "Texture search base (S43: upward search over textures/ + sprites/)."},
    {"milkdrop.pufferAusblendSek",
     "Ausblenden: Dauer in Sekunden, ueber die das Erbe wegstirbt (Echo je Frame zusaetzlich gedaempft); nur im Modus Ausblenden wirksam."},
    {"milkdrop.pufferFading",
     "Fading: Anteil des ERBES 0..1 (0 = wie Loeschen, 1 = wie Behalten); nur im Modus Fading wirksam."},
    {"milkdrop.pufferWechsel",
     "Puffer-Verhalten beim .milk\342\206\222.milk-Wechsel \342\200\224 Node-Einstellung, ueberlebt den In-Place-Preset-Tausch (wie meshX/meshY). Persistiert im Chain-Doc."},
    {"mirror.beatCode",
     "Parameter-Skript (Strang D): `mode`, `slower` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"mirror.frameCode",
     "Parameter-Skript (Strang D): `mode`, `slower` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"mirror.initCode",
     "Parameter-Skript (Strang D): `mode`, `slower` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"mirror.mode",
     "r_mirror direction bits: 1 = top->bottom (HORIZONTAL1), 2 = bottom->top (HORIZONTAL2), 4 = left->right (VERTICAL1), 8 = right->left (VERTICAL2)"},
    {"mirror.onBeatRandom",
     "randomize active edges on beat"},
    {"mirror.slower",
     "frames per ramp step (1..16)"},
    {"mirror.smooth",
     "gradual transition (BLEND_ADAPT ramp)"},
    {"mosaic.beatCode",
     "Parameter-Skript (Strang D): `quality`, `quality2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"mosaic.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"mosaic.durationFrames",
     "ease-back length in frames (>= 1)"},
    {"mosaic.frameCode",
     "Parameter-Skript (Strang D): `quality`, `quality2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"mosaic.initCode",
     "Parameter-Skript (Strang D): `quality`, `quality2` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"mosaic.onBeat",
     "jump to quality2 on beat, then ease back"},
    {"mosaic.quality",
     "block resolution 1..100 (100 = off)"},
    {"mosaic.quality2",
     "on-beat resolution 1..100"},
    {"movement.blend",
     "50/50 blend of moved pixel with original (r_trans)"},
    {"movement.builtinRemap",
     "r_trans builtins WITHOUT eval_desc (pixel-index remaps, no d/r formula): 1 = \"slight fuzzify\", 7 = \"blocky partial out\"; 0 = code/formula path."},
    {"movement.code",
     "AVS point expression (empty = identity)"},
    {"movement.rectCoords",
     "true = x/y, false (AVS default) = polar d/r"},
    {"movement.sourceMapped",
     "r_trans sourcemapped bits: 1 = scatter-write (source pixel is PUSHED to its target, MAX-blended), 2 = toggle bit 1 on every beat"},
    {"movement.subpixel",
     "bilinear (on) vs nearest (off) source sampling"},
    {"movement.wrap",
     "wrap sampling coordinates instead of clamp"},
    {"movingParticle.beatCode",
     "Parameter-Skript (Strang D): `size`, `size2`, `maxdistance`, `spring`, `damping`. Klasse A \342\200\224 s. Hinweis bei `DotPlaneParams`."},
    {"movingParticle.blend",
     "0 replace, 1 additive, 2 50/50, 3 line"},
    {"movingParticle.color",
     "particle colour 0x00RRGGBB"},
    {"movingParticle.damping",
     "Geschwindigkeitsdaempfung (Original 0,991)"},
    {"movingParticle.frameCode",
     "Parameter-Skript (Strang D): `size`, `size2`, `maxdistance`, `spring`, `damping`. Klasse A \342\200\224 s. Hinweis bei `DotPlaneParams`."},
    {"movingParticle.initCode",
     "Parameter-Skript (Strang D): `size`, `size2`, `maxdistance`, `spring`, `damping`. Klasse A \342\200\224 s. Hinweis bei `DotPlaneParams`."},
    {"movingParticle.maxDistance",
     "travel-radius scale (AVS maxdist)"},
    {"movingParticle.onBeatSize",
     "jump to size2 on beat (AVS enabled bit 1)"},
    {"movingParticle.size",
     "particle radius (px)"},
    {"movingParticle.size2",
     "on-beat radius"},
    {"movingParticle.spring",
     "Zug zum Ziel je Frame (Original 0,004)"},
    {"multiDelay.beatCode",
     "Parameter-Skript (Strang D): `delay`, `buffer` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiDelay.buffer",
     "shared buffer index 0..5"},
    {"multiDelay.delay",
     "delay length"},
    {"multiDelay.frameCode",
     "Parameter-Skript (Strang D): `delay`, `buffer` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiDelay.initCode",
     "Parameter-Skript (Strang D): `delay`, `buffer` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiDelay.mode",
     "0 none, 1 input, 2 output"},
    {"multiDelay.useBeats",
     "delay in beats vs frames"},
    {"multiFilter.beatCode",
     "Parameter-Skript (Strang D): `effect` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiFilter.effect",
     "0 chrome, 1 double chrome, 2 triple chrome, 3 root"},
    {"multiFilter.frameCode",
     "Parameter-Skript (Strang D): `effect` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiFilter.initCode",
     "Parameter-Skript (Strang D): `effect` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiFilter.onBeat",
     "apply only on beat frames"},
    {"multiplier.beatCode",
     "Parameter-Skript (Strang D): `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiplier.frameCode",
     "Parameter-Skript (Strang D): `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiplier.initCode",
     "Parameter-Skript (Strang D): `mode` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"multiplier.mode",
     "0..7 (see above)"},
    {"onBeatClear.beatCode",
     "Parameter-Skript (Strang D): `everyNBeats` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"onBeatClear.blend",
     "50/50 towards color instead of hard clear"},
    {"onBeatClear.color",
     "clear color 0x00RRGGBB"},
    {"onBeatClear.everyNBeats",
     "N (>= 1)"},
    {"onBeatClear.frameCode",
     "Parameter-Skript (Strang D): `everyNBeats` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"onBeatClear.initCode",
     "Parameter-Skript (Strang D): `everyNBeats` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscRing.audioScale",
     "Audio-Anteil am Radius (war fest 0,9)"},
    {"oscRing.baseScale",
     "Radius-Sockel ohne Audio (war fest 0,1)"},
    {"oscRing.beatCode",
     "Parameter-Skript (Strang D): `size`, `segments`, `basescale`, `audioscale` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscRing.channel",
     "0 L, 1 R, 2 center"},
    {"oscRing.colors",
     "Farbtafel (0x00RRGGBB), ueber die Frames durchgeschaltet."},
    {"oscRing.frameCode",
     "Parameter-Skript (Strang D): `size`, `segments`, `basescale`, `audioscale` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscRing.initCode",
     "Parameter-Skript (Strang D): `size`, `segments`, `basescale`, `audioscale` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscRing.position",
     "0 left, 1 right, 2 center"},
    {"oscRing.segments",
     "Stuetzpunkte des Rings (war fest 80)"},
    {"oscRing.size",
     "base radius 0..16"},
    {"oscRing.source",
     "0 waveform, 1 spectrum"},
    {"oscStar.amplitude",
     "Faktor auf den Wellenausschlag (Referenz 1)"},
    {"oscStar.beatCode",
     "Parameter-Skript (Strang D): `size`, `rot`, `spokes`, `rotscale`, `amplitude` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscStar.channel",
     "0 L, 1 R, 2 center (signed-halbierte Summe wie die Referenz)"},
    {"oscStar.colors",
     "Farbtafel (0x00RRGGBB), ueber die Frames durchgeschaltet."},
    {"oscStar.frameCode",
     "Parameter-Skript (Strang D): `size`, `rot`, `spokes`, `rotscale`, `amplitude` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscStar.initCode",
     "Parameter-Skript (Strang D): `size`, `rot`, `spokes`, `rotscale`, `amplitude` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"oscStar.position",
     "0 left (w/4), 1 right (3w/4), 2 center"},
    {"oscStar.rot",
     "rotation speed (r_oscstar: m_r += 0.01*rot; 0 = still)"},
    {"oscStar.rotScale",
     "Bogenmass je `rot`-Einheit und Frame (Referenz 0,01)"},
    {"oscStar.size",
     "spoke length 0..16 (r_oscstar: s = size/32)"},
    {"oscStar.spokes",
     "Zahl der Speichen (Referenz fest 5)"},
    {"passthrough.note",
     "import report text (\"effect X not implemented\")"},
    {"passthrough.sourceId",
     "original AVS effect id (or 0 if hand-built)"},
    {"picture.beatCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"picture.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"picture.filename",
     "original AVS filename (reference only)"},
    {"picture.frameCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"picture.imageData",
     "base64 of the raw image file (\"\" = unresolved)"},
    {"picture.initCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"picture.keepAspect",
     "preserve the image aspect (letterbox)"},
    {"pictureII.beatCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"pictureII.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"pictureII.filename",
     "Herkunftsnotiz aus dem Preset. Gezeichnet wird `imageData`; von diesem Pfad wird nie geladen."},
    {"pictureII.frameCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"pictureII.imageData",
     "base64 of the raw image (\"\" = unresolved)"},
    {"pictureII.initCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"reactionDiffusion.beatCode",
     "Parameter-Skript (Strang D): `feed`, `kill` + Audio-Satz \342\200\224 damit wandert das Muster im Betrieb. Leer = kein Skript."},
    {"reactionDiffusion.blend",
     "Auf das bestehende Bild: 0 ersetzen, 1 additiv (geklemmt), 2 50/50."},
    {"reactionDiffusion.colorCycle",
     "Vorschub der Farbphase je Sekunde (0 = stehende Farben)."},
    {"reactionDiffusion.colorScale",
     "Faerbung: Farbtafel-Index = `fract(Konzentration von B * colorScale + Phase)`."},
    {"reactionDiffusion.diffA",
     "diffusion rate of A"},
    {"reactionDiffusion.diffB",
     "diffusion rate of B"},
    {"reactionDiffusion.feed",
     "feed rate"},
    {"reactionDiffusion.frameCode",
     "Parameter-Skript (Strang D): `feed`, `kill` + Audio-Satz \342\200\224 damit wandert das Muster im Betrieb. Leer = kein Skript."},
    {"reactionDiffusion.gradientPreset",
     "Name des Farbverlaufs, ueber den die Konzentration abgebildet wird."},
    {"reactionDiffusion.initCode",
     "Parameter-Skript (Strang D): `feed`, `kill` + Audio-Satz \342\200\224 damit wandert das Muster im Betrieb. Leer = kein Skript."},
    {"reactionDiffusion.kill",
     "kill rate"},
    {"reactionDiffusion.seedOnBeat",
     "stamp a new seed blob on a beat"},
    {"reactionDiffusion.stepsPerFrame",
     "sim iterations per rendered frame"},
    {"renderScale.divisor",
     "interne Aufloesung = Fenster / divisor (1..8)"},
    {"renderScale.filter",
     "Upscale: 0 = nearest (authentisch grob), 1 = linear"},
    {"rotatingStars.audioGain",
     "Zuwachs aus der Spektrumsspitze (255/352, s. baseRadius)"},
    {"rotatingStars.bandHi",
     "erstes NICHT mehr ausgewertetes Band"},
    {"rotatingStars.bandLo",
     "erstes ausgewertetes Spektralband (Lokal-Peak-Suche)"},
    {"rotatingStars.baseRadius",
     "Sterngroesse ohne Audio, je Achse in NDC. Die Referenz rechnet w/8*(s+9)/88 (r_rotstar:145) = (s+9)/352 in NDC \342\200\224 die Vorgaben 9/352 und 255/352 stellen bei Default exakt diese Formel her (S60)."},
    {"rotatingStars.beatCode",
     "Parameter-Skript (Strang D): rechnet die Regler je Frame aus. Lesbare und schreibbare Namen sind die Feldnamen in Kleinschreibung (`points`, `skip`, `stars`, `rotspeed`, `orbit`, `baseradius`, `audiogain`), dazu `b`/`w`/`h` und der Audio-Satz. Leer = kein Skript."},
    {"rotatingStars.colors",
     "Farbtafel (0x00RRGGBB), ueber die Frames durchgeschaltet."},
    {"rotatingStars.frameCode",
     "Parameter-Skript (Strang D): rechnet die Regler je Frame aus. Lesbare und schreibbare Namen sind die Feldnamen in Kleinschreibung (`points`, `skip`, `stars`, `rotspeed`, `orbit`, `baseradius`, `audiogain`), dazu `b`/`w`/`h` und der Audio-Satz. Leer = kein Skript."},
    {"rotatingStars.initCode",
     "Parameter-Skript (Strang D): rechnet die Regler je Frame aus. Lesbare und schreibbare Namen sind die Feldnamen in Kleinschreibung (`points`, `skip`, `stars`, `rotspeed`, `orbit`, `baseradius`, `audiogain`), dazu `b`/`w`/`h` und der Audio-Satz. Leer = kein Skript."},
    {"rotatingStars.orbit",
     "Abstand vom Bildmittelpunkt (NDC; 0,5 = w/4 wie das Original)"},
    {"rotatingStars.points",
     "Zacken je Stern (war fest 5)"},
    {"rotatingStars.rotSpeed",
     "Bahndrehung je Frame (r_rotstar: r1 += 0.1)"},
    {"rotatingStars.skip",
     "Sprungweite beim Zeichnen; 2 = Pentagramm"},
    {"rotatingStars.stars",
     "Zahl der Sterne auf gegenueberliegenden Bahnen"},
    {"rotoBlitter.beatCode",
     "Parameter-Skript (Strang D): `zoomscale`, `zoomscale2`, `rotdir` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"rotoBlitter.beatReverse",
     "Beat kehrt die Drehrichtung um"},
    {"rotoBlitter.beatReverseSpeed",
     "Ease des Richtungswechsels (0 = hart)"},
    {"rotoBlitter.beatZoomJump",
     "Beat setzt fpos = zoomScale2"},
    {"rotoBlitter.blend",
     "BLEND_AVG mit dem Original"},
    {"rotoBlitter.frameCode",
     "Parameter-Skript (Strang D): `zoomscale`, `zoomscale2`, `rotdir` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"rotoBlitter.initCode",
     "Parameter-Skript (Strang D): `zoomscale`, `zoomscale2`, `rotdir` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"rotoBlitter.rotDir",
     "theta = (rotDir-32) Grad je Frame"},
    {"rotoBlitter.subpixel",
     "bilineares Sampling (BLEND4)"},
    {"rotoBlitter.zoomScale",
     "Zoom-Zielwert (31 = neutral)"},
    {"rotoBlitter.zoomScale2",
     "Beat-Zoomwert (beatZoomJump)"},
    {"setRenderMode.adjustAlpha",
     "Adjustable-blend alpha 0..255"},
    {"setRenderMode.lineBlend",
     "AVS BLEND_LINE mode 0..9 (S9)"},
    {"setRenderMode.lineWidth",
     "line width for following scopes (px, 0 = leave)"},
    {"setRenderMode.overrideBlend",
     "override the blend (AVS bit 31)"},
    {"shadertoy.blend",
     "aufs Bild: 0 ersetzen, 1 additiv, 2 50/50"},
    {"shadertoy.code",
     "mainImage-Quelltext des Image-Passes (leer = Starter)"},
    {"shadertoy.imageInput",
     "Kanal-Bindungen des Image-Passes (Kodierung s. kShadertoyInput* \342\200\224 SSOT; ein fr\303\274hes `audioChannel`-Feld wird beim Laden migriert)."},
    {"simpleScope.beatCode",
     "Parameter-Skript (Strang D): `mode`, `channel`, `position` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"simpleScope.channel",
     "0 L, 1 R, 2 center (Byte-Halbierung wie Original)"},
    {"simpleScope.colors",
     "Farbtafel (0x00RRGGBB), ueber die Frames durchgeschaltet."},
    {"simpleScope.frameCode",
     "Parameter-Skript (Strang D): `mode`, `channel`, `position` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"simpleScope.initCode",
     "Parameter-Skript (Strang D): `mode`, `channel`, `position` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"simpleScope.mode",
     "0 solid ana, 1 line ana, 2 line scope, 3 solid scope,"},
    {"simpleScope.position",
     "0 top, 1 bottom, 2 center"},
    {"starfield.beatCode",
     "Parameter-Skript (Strang D): `maxstars`, `warpspeed`, `beatspeed`, `durationframes` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"starfield.beatSpeed",
     "on-beat speed"},
    {"starfield.blend",
     "0 replace, 1 additive, 2 50/50 (r_stars)"},
    {"starfield.color",
     "tint 0x00RRGGBB"},
    {"starfield.durationFrames",
     "ease-back length"},
    {"starfield.frameCode",
     "Parameter-Skript (Strang D): `maxstars`, `warpspeed`, `beatspeed`, `durationframes` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"starfield.initCode",
     "Parameter-Skript (Strang D): `maxstars`, `warpspeed`, `beatspeed`, `durationframes` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"starfield.maxStars",
     "star count"},
    {"starfield.onBeat",
     "jump to beatSpeed on a beat"},
    {"starfield.warpSpeed",
     "base fly-through speed"},
    {"strangeAttractor.a",
     "Erster Formelbeiwert. Was er bedeutet, haengt am `type`: Lorenz sigma (x7,142857), Clifford/De Jong der Faktor im Sinus, Aizawa der z-Term."},
    {"strangeAttractor.b",
     "Zweiter Beiwert: Lorenz rho (x17,5), Clifford/De Jong der zweite Sinus-/Kosinus-Faktor, Aizawa die z-Verschiebung."},
    {"strangeAttractor.beatCode",
     "Parameter-Skript (Strang D): `a`, `b`, `c`, `d`, `rotation` + Audio-Satz. Leer = kein Skript. Achtung: eine Aenderung der Beiwerte im Panel setzt den Traeger neu auf und laesst den Init-Slot erneut laufen."},
    {"strangeAttractor.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"strangeAttractor.c",
     "Dritter Beiwert: Lorenz beta (x2,6667), Clifford der Kosinus-Anteil in x, De Jong der Sinus-Faktor in y, Aizawa das konstante Glied."},
    {"strangeAttractor.color",
     "Punktfarbe 0x00RRGGBB, wenn `useGradient` aus ist."},
    {"strangeAttractor.d",
     "Vierter Beiwert: Clifford/De Jong der Kosinus-Anteil in y, Aizawa die Drehung in der xy-Ebene. Lorenz nutzt ihn nicht."},
    {"strangeAttractor.dotSize",
     "Punktdurchmesser in Pixeln (1..32)."},
    {"strangeAttractor.frameCode",
     "Parameter-Skript (Strang D): `a`, `b`, `c`, `d`, `rotation` + Audio-Satz. Leer = kein Skript. Achtung: eine Aenderung der Beiwerte im Panel setzt den Traeger neu auf und laesst den Init-Slot erneut laufen."},
    {"strangeAttractor.ftype",
     "0 Lorenz 1 Clifford 2 De Jong 3 Aizawa"},
    {"strangeAttractor.gradientPreset",
     "Name des Farbverlaufs fuer `useGradient` \342\200\224 die Bahn wird von Anfang bis Ende darueber eingefaerbt."},
    {"strangeAttractor.initCode",
     "Parameter-Skript (Strang D): `a`, `b`, `c`, `d`, `rotation` + Audio-Satz. Leer = kein Skript. Achtung: eine Aenderung der Beiwerte im Panel setzt den Traeger neu auf und laesst den Init-Slot erneut laufen."},
    {"strangeAttractor.points",
     "Punkte je Frame (1..100000). Die Bahn laeuft ueber Frames weiter \342\200\224 mehr Punkte heisst dichter gezeichnet, nicht laenger."},
    {"strangeAttractor.rotation",
     "Fester Drehwinkel der Ansicht in Radiant, addiert zur laufenden Drehung."},
    {"strangeAttractor.rotationSpeed",
     "Laufende Drehung in Radiant je Sekunde (0 = steht still)."},
    {"strangeAttractor.scale",
     "Groesse der Bahn im Bild (Faktor auf die Koordinaten, vor der Drehung)."},
    {"strangeAttractor.useGradient",
     "colour dots along the orbit via the gradient"},
    {"superScope.audioChannel",
     "0=L 1=R 2=mono 3=mid 4=side"},
    {"superScope.beatCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Punktzahl); der Punkt-Code laeuft je Punkt."},
    {"superScope.colorBlend",
     "0 gradient, 1 table, 2 additive, 3 multiply, 4 average"},
    {"superScope.colorCycleFrames",
     "frames per table step (>= 1)"},
    {"superScope.colors",
     "AVS color table (0x00RRGGBB), cycled"},
    {"superScope.dotSize",
     "Punktdurchmesser in Pixeln fuer `renderMode` 0."},
    {"superScope.frameCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Punktzahl); der Punkt-Code laeuft je Punkt."},
    {"superScope.gradientPreset",
     "ColorGradientModule preset name"},
    {"superScope.initCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Punktzahl); der Punkt-Code laeuft je Punkt."},
    {"superScope.lineBlend",
     "AVS BLEND_LINE mode 0..9 (S9; s. SetRenderModeParams)"},
    {"superScope.lineWidth",
     "Strichstaerke in Pixeln fuer `renderMode` 1/2; `linesize` aus dem Punkt-Code gewinnt."},
    {"superScope.pointCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Punktzahl); der Punkt-Code laeuft je Punkt. Laeuft je Punkt: `i` 0..1 und `v` (Audio) herein, gelesen werden `x`/`y` (-1..1), `red`/`green`/`blue`, `linesize`, `skip` und `drawmode`."},
    {"superScope.pointCount",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n` (Punktzahl); der Punkt-Code laeuft je Punkt. Laeuft je Punkt: `i` 0..1 und `v` (Audio) herein, gelesen werden `x`/`y` (-1..1), `red`/`green`/`blue`, `linesize`, `skip` und `drawmode`. Startwert fuer `n` \342\200\224 der Punkt-Code laeuft so oft. Ein Skript, das `n` selbst setzt, gewinnt."},
    {"superScope.renderMode",
     "0=dots, 1=lines, 2=thick lines"},
    {"superScope.spectrumSource",
     "AVS which_ch bit 4 (r_sscope.cpp:232): v liest SPEKTRUM statt Waveform."},
    {"superScope3d.audioChannel",
     "v-Quelle: 0 = links, 1 = rechts, 2 = mono"},
    {"superScope3d.beatCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n`; der Punkt-Code laeuft je Punkt."},
    {"superScope3d.falloff",
     "Sprite-Profil k in exp(-r^2*k)"},
    {"superScope3d.frameCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n`; der Punkt-Code laeuft je Punkt."},
    {"superScope3d.initCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n`; der Punkt-Code laeuft je Punkt."},
    {"superScope3d.pointCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen unter anderem `n`; der Punkt-Code laeuft je Punkt. Laeuft je Punkt: `i` 0..1 und `v` (Audio) herein, gelesen werden `x`, `y`, `z` (Weltkoordinaten), `red`/`green`/`blue` und `size`."},
    {"superScope3d.pointCount",
     "Default-n (Skript-n ueberschreibt)"},
    {"superScope3d.renderMode",
     "0 = Soft-Sprites (Punkte), 1 = Linien"},
    {"superScope3d.size",
     "Default-Punktgroesse (Welt-Einheiten)"},
    {"superScope3d.spectrumSource",
     "v liest Spektrum statt Waveform"},
    {"tentacles3d.beatCode",
     "Parameter-Skript (Strang D): `count`, `segments`, `length`, `thickness`, `speed`, `sway`, `waves`, `taper` + `b`/`w`/`h` + Audio-Satz."},
    {"tentacles3d.blend",
     "0 replace, 1 additiv, 2 50/50"},
    {"tentacles3d.colors",
     "Palette (0x00RRGGBB). NICHT leer: der Leser heilt eine leere Tafel auf Weiss, eine leere liesse sich also gar nicht speichern (Roundtrip-Befund S56). Die Vorgabe sagt es deshalb selbst."},
    {"tentacles3d.count",
     "Zahl der Tentakel (1..16)"},
    {"tentacles3d.frameCode",
     "Parameter-Skript (Strang D): `count`, `segments`, `length`, `thickness`, `speed`, `sway`, `waves`, `taper` + `b`/`w`/`h` + Audio-Satz."},
    {"tentacles3d.initCode",
     "Parameter-Skript (Strang D): `count`, `segments`, `length`, `thickness`, `speed`, `sway`, `waves`, `taper` + `b`/`w`/`h` + Audio-Satz."},
    {"tentacles3d.length",
     "Laenge in NDC"},
    {"tentacles3d.segments",
     "Stuetzpunkte je Tentakel"},
    {"tentacles3d.speed",
     "Schwinggeschwindigkeit"},
    {"tentacles3d.sway",
     "Schwingweite an der Spitze (war fest 0,9)"},
    {"tentacles3d.taper",
     "Verjuengung zur Spitze; 0 = gleich dick"},
    {"tentacles3d.thickness",
     "Linienbreite an der Wurzel (Pixel)"},
    {"tentacles3d.waves",
     "Wellen ueber die Laenge (war fest 3,1)"},
    {"terrain3d.baseAmp",
     "Amplitude der prozeduralen Basis"},
    {"terrain3d.beatCode",
     "EEL-Slots fuer das Gelaende; sie teilen sich ihre Variablen mit dem Punkt-Code darunter."},
    {"terrain3d.colorHigh",
     "Palette: Gipfel"},
    {"terrain3d.colorLow",
     "Palette: Tal"},
    {"terrain3d.dotSize",
     "Welt-Einheiten"},
    {"terrain3d.drawDots",
     "additive Soft-Sprites an den Gitterpunkten"},
    {"terrain3d.drawMesh",
     "dunkles Mesh (opak, schreibt Depth)"},
    {"terrain3d.extent",
     "Weltbreite/-tiefe des Grids"},
    {"terrain3d.falloff",
     "Sprite-Profil k"},
    {"terrain3d.flatten",
     "direkter Zug Richtung Basis je Frame (0..1)"},
    {"terrain3d.frameCode",
     "EEL-Slots fuer das Gelaende; sie teilen sich ihre Variablen mit dem Punkt-Code darunter."},
    {"terrain3d.initCode",
     "EEL-Slots fuer das Gelaende; sie teilen sich ihre Variablen mit dem Punkt-Code darunter."},
    {"terrain3d.meshColor",
     "Farbe des Gitters 0x00RRGGBB"},
    {"terrain3d.pointCode",
     "je Gitterpunkt: Farbe (red/green/blue)"},
    {"terrain3d.relax",
     "Feder-Relaxation zur Basis (0..1)"},
    {"terrain3d.resolution",
     "Gitterpunkte je Achse (8..128)"},
    {"terrain3d.ringAmp",
     "Spektrum-Ring-Injektion je Frame (0 = aus)"},
    {"terrain3d.yOffset",
     "Grundhoehe (Welt-y)"},
    {"texer.beatCode",
     "Parameter-Skript (Strang D): `blend`, `particles` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"texer.blend",
     "0 ersetzen, 1 additiv, 2 50/50."},
    {"texer.filename",
     "Herkunftsnotiz aus dem Preset. Gezeichnet wird `imageData`; von diesem Pfad wird nie geladen."},
    {"texer.frameCode",
     "Parameter-Skript (Strang D): `blend`, `particles` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"texer.imageData",
     "Das eingebettete Bild (base64). Leer = eingebautes Standard-Sprite."},
    {"texer.initCode",
     "Parameter-Skript (Strang D): `blend`, `particles` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"texer.particles",
     "Anzahl der Sprites entlang der Wellenform."},
    {"texerII.beatCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Sprites); der Punkt-Code laeuft je Sprite."},
    {"texerII.colorFiltering",
     "`red`/`green`/`blue` aus dem Punkt-Code als Farbfilter auf das Bild legen (aus: das Bild wird unveraendert gezeichnet)."},
    {"texerII.filename",
     "Herkunftsnotiz aus dem Preset. Gezeichnet wird `imageData`; von diesem Pfad wird nie geladen."},
    {"texerII.frameCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Sprites); der Punkt-Code laeuft je Sprite."},
    {"texerII.imageData",
     "Das eingebettete Bild (base64). Leer = eingebautes Standard-Sprite (20x20, radialsymmetrisch \342\200\224 gemessen gegen die echte texer2.ape)."},
    {"texerII.initCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Sprites); der Punkt-Code laeuft je Sprite."},
    {"texerII.pointCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Sprites); der Punkt-Code laeuft je Sprite. Laeuft je Sprite: `i` 0..1 herein, gelesen werden `x`/`y` (-1..1), `sizex`/`sizey` (nur mit `resizing`) und `red`/`green`/`blue` (nur mit `colorFiltering`)."},
    {"texerII.resizing",
     "`sizex`/`sizey` aus dem Punkt-Code wirken lassen (aus: feste Groesse)."},
    {"texerII.wrapAround",
     "Sprites am Bildrand auf der Gegenseite fortsetzen statt abzuschneiden."},
    {"text.blend",
     "0 replace, 1 additive, 2 50/50 (glyphs only)"},
    {"text.color",
     "Schriftfarbe 0x00RRGGBB"},
    {"text.fontFace",
     "LOGFONT lfFaceName (\"\" = default font)"},
    {"text.fontHeight",
     "LOGFONT lfHeight (negative = px char height)"},
    {"text.fontWeight",
     "400 normal, 700 bold"},
    {"text.hAlign",
     "0 left, 1 center, 2 right"},
    {"text.insertBlank",
     "blank frame between words"},
    {"text.italic",
     "LOGFONT lfItalic \342\200\224 kursiv"},
    {"text.normSpeed",
     "frames per word in timer mode"},
    {"text.onBeat",
     "word switches on beat instead of timer"},
    {"text.onBeatSpeed",
     "frames a beat-word stays visible"},
    {"text.outline",
     "Kontur um die Zeichen zeichnen"},
    {"text.outlineColor",
     "Konturfarbe 0x00RRGGBB"},
    {"text.outlineSize",
     "Konturbreite in Pixeln"},
    {"text.randomPos",
     "random position per word"},
    {"text.randomWord",
     "random instead of sequential word pick"},
    {"text.shadow",
     "shadow variant (outline wins if both)"},
    {"text.text",
     "words separated by ';'"},
    {"text.underline",
     "LOGFONT lfUnderline \342\200\224 unterstrichen"},
    {"text.vAlign",
     "0 top, 1 center, 2 bottom"},
    {"text.xShift",
     "percent of width"},
    {"text.yShift",
     "percent of height"},
    {"timescope.bands",
     "vertical spectrum resolution"},
    {"timescope.beatCode",
     "Parameter-Skript (Strang D): `bands`, `channel`, `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"timescope.blend",
     "0 replace, 1 additive, 2 50/50, 3 BLEND_LINE (folgt dem Set-Render-Mode- Zustand \342\200\224 AVS-Default \"Default Blend\", r_timescope.cpp:147-148, S3)"},
    {"timescope.channel",
     "0 L, 1 R, 2 center"},
    {"timescope.color",
     "tint 0x00RRGGBB"},
    {"timescope.frameCode",
     "Parameter-Skript (Strang D): `bands`, `channel`, `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"timescope.initCode",
     "Parameter-Skript (Strang D): `bands`, `channel`, `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"timescope.useChannel",
     "`channel` wirklich anwenden (Erweiterung, Vorgabe AUS = referenztreu)."},
    {"triangle.beatCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Dreiecke); der Punkt-Code laeuft je Dreieck."},
    {"triangle.filled",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Dreiecke); der Punkt-Code laeuft je Dreieck. Laeuft je Dreieck: gelesen werden `x1`/`y1`, `x2`/`y2`, `x3`/`y3` (-1..1) und `red`/`green`/`blue`. GEFUELLT ist der Referenz-Zustand (Sonde `triangle_n_literal`, S51: das fruehere Drahtgitter lieferte 4009 statt 23424 Pixel). `false` ist damit eine bewusste Abweichung von AVS, kein Alternativ-Default."},
    {"triangle.frameCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Dreiecke); der Punkt-Code laeuft je Dreieck."},
    {"triangle.initCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Dreiecke); der Punkt-Code laeuft je Dreieck."},
    {"triangle.lineWidth",
     "Kantenbreite im Drahtgitter-Modus"},
    {"triangle.pointCode",
     "EEL-Quartett. init/frame/beat laufen einmal je Aufbau/Frame/Beat und setzen `n` (Anzahl Dreiecke); der Punkt-Code laeuft je Dreieck. Laeuft je Dreieck: gelesen werden `x1`/`y1`, `x2`/`y2`, `x3`/`y3` (-1..1) und `red`/`green`/`blue`."},
    {"uniqueTone.beatCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"uniqueTone.blend",
     "0 replace, 1 additive, 2 50/50"},
    {"uniqueTone.color",
     "tone colour 0x00RRGGBB"},
    {"uniqueTone.frameCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"uniqueTone.initCode",
     "Parameter-Skript (Strang D): `blend` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"uniqueTone.invert",
     "invert the depth ramp"},
    {"videoDelay.beatCode",
     "Parameter-Skript (Strang D): `delay` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"videoDelay.delay",
     "delay amount (frames, capped for VRAM)"},
    {"videoDelay.frameCode",
     "Parameter-Skript (Strang D): `delay` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"videoDelay.initCode",
     "Parameter-Skript (Strang D): `delay` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"videoDelay.useBeats",
     "delay in beats vs frames"},
    {"waterBump.beatCode",
     "Parameter-Skript (Strang D): `density`, `depth`, `dropradius`, `displacescale` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"waterBump.density",
     "wave damping (higher = longer-lived waves)"},
    {"waterBump.depth",
     "drop amplitude"},
    {"waterBump.displaceScale",
     "Verstaerkung des Versatzes. Seit der Ganzzahl-Umstellung (S59) stehen die Hoehen in REFERENZ-Einheiten \342\200\224 1.0 = exakt r_waterbump; der alte Wert 6.0 stammte aus der normierten Aera und verzerrte 6-fach."},
    {"waterBump.dropRadius",
     "drop radius (px)"},
    {"waterBump.dropX",
     "0 near / 1 mid / 2 far (position code)"},
    {"waterBump.dropY",
     "dito senkrecht: 0 oben / 1 Mitte / 2 unten"},
    {"waterBump.frameCode",
     "Parameter-Skript (Strang D): `density`, `depth`, `dropradius`, `displacescale` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"waterBump.initCode",
     "Parameter-Skript (Strang D): `density`, `depth`, `dropradius`, `displacescale` + `b`/`w`/`h` + Audio-Satz. Leer = kein Skript."},
    {"waterBump.randomDrop",
     "random drop spot vs. fixed dropX/dropY"},
}};
}  // namespace

QString tooltip(const QString& typeKey, const QString& field)
{
    const std::string key = (typeKey + QLatin1Char('.') + field).toStdString();
    const std::string_view needle{key};
    const auto it = std::lower_bound(
        kDocs.begin(), kDocs.end(), needle,
        [](const auto& e, std::string_view n) { return e.first < n; });
    if (it == kDocs.end() || it->first != needle) return {};
    return QString::fromUtf8(it->second.data(),
                             static_cast<int>(it->second.size()));
}

QStringList documentedKeys()
{
    QStringList out;
    out.reserve(static_cast<int>(kDocs.size()));
    for (const auto& [key, text] : kDocs)
        out << QString::fromUtf8(key.data(), static_cast<int>(key.size()));
    return out;
}

}  // namespace lumi::multieffect::fielddocs
